# ============================================================================
# Demo Wallet Helm Chart Values
# Uses bjw-s app-template for standardized deployment
# ============================================================================

# Reusable anchors

globals:
  image: &walletImage
    repository: ghcr.io/adorsys-gis/wallet-vc
    tag: latest@sha256:530d98d21a2172b2cc0fe5dde85c6778bcb675bc6b1f78b1368fb35ebea03f8f
    pullPolicy: Always
  ingressHost: &ingressHost 'demo-wallet.eudi-adorsys.com'
  tlsHosts: &tlsHosts
  - '*.eudi-adorsys.com'
  - 'eudi-adorsys.com'
# ============================================================================
app-template:
  global:
    fullnameOverride: demo-wallet
    namespace: datev-wallet
    labels:
      app: demo-wallet
  defaultPodOptions:
    imagePullSecrets:
    - name: ghcr-pull-secret
  controllers:
    wallet:
      type: deployment
      replicas: 1
      containers:
        app:
          nameOverride: demo-wallet-app
          image: *walletImage
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  service:
    app:
      enabled: true
      type: ClusterIP
      controller: wallet
      ports:
        http:
          enabled: true
          port: 8081
          protocol: HTTP
          targetPort: 8080
  ingress:
    app:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: *ingressHost
      hosts:
      - host: *ingressHost
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: app
            port: 8081
      tls:
      - secretName: eudi-adorsys-tls
        hosts: *tlsHosts
