apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wallet-chart.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsHostname }}
    {{- toYaml .Values.wallet.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.wallet.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.dnsHostname }}
    http:
      paths:
      - path: {{ .Values.wallet.ingress.path }}
        pathType: {{ .Values.wallet.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.fullnameOverride }}-service
            port:
              number: {{ .Values.wallet.service.port }}
  tls:
  - hosts:
    {{- range .Values.wallet.ingress.tls.hosts }}
      - {{ . | quote }}
    {{- end }}
    secretName: {{ .Values.wallet.ingress.secretName }}