apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-chart.fullname" . }}-service
  labels:
    app: {{ include "wallet-chart.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.wallet.service.type }}
  ports:
  - name: https
    port: {{ .Values.wallet.service.port }}
    targetPort: {{ .Values.wallet.service.targetPort }}
  selector:
    app: {{ include "wallet-chart.name" . }}