name: ArgoCD Image Updater Auto PR

on:
  push:
    branches:
      - image-updates

env:
  node_version: 20.x
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  auto-fix:
    # Skip only if the last commit is the auto-fix commit to avoid infinite loop
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: auto-fix formatting') }}"
    name: Auto-fix Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Auto-fix formatting & lint issues
        run: npm run format

      - name: Commit and push fixes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: auto-fix formatting and linting"
            git push \
              "https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" \
              HEAD:${GITHUB_REF_NAME}
          fi

  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: auto-fix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_PAT }}

      - name: Extract commit message
        id: split-message
        run: |
          FULL_MESSAGE="$(git log -1 --pretty=%B)"
          TITLE="$(echo "$FULL_MESSAGE" | head -n 1)"
          BODY="$(echo "$FULL_MESSAGE" | tail -n +2)"

          {
            echo "title<<EOF"
            echo "$TITLE"
            echo "EOF"
            echo "body<<EOF"
            echo "$BODY"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: 'image-updates'
          destination_branch: 'main'
          pr_title: ${{ steps.split-message.outputs.title }}
          pr_body: |
            This pull request updates container images for the application, as detected by **Argo CD Image Updater**.

            **Changes:**
            ${{ steps.split-message.outputs.body }}
          pr_label: 'auto-pr'
          pr_reviewer: 'Awambeng'
          github_token: ${{ env.GH_PAT }}
