name: Create PR for Image Updates

on:
  push:
    branches:
      - image-updates

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create Pull Request using REST API
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls"

          # Check if PR already exists
          PR_EXISTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $API_URL?head=${{ github.repository_owner }}:image-updates | jq '.[0].number // empty')

          if [ -z "$PR_EXISTS" ]; then
            echo "Creating pull request..."
            curl -X POST "$API_URL" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "title": "Automated image updates",
                "head": "image-updates",
                "base": "main",
                "body": "This PR contains automated updates to image versions."
              }'
          else
            echo "PR already exists: #$PR_EXISTS"
          fi
