name: Create PR for Image Updates
on:
  push:
    branches:
      - image-updates
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Debug Token
        run: |
          echo "Checking authentication status..."
          gh auth status
      - name: Check for Existing PR
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          existing_pr=$(gh pr list --base develop --head image-updates --state open --json number --jq '.[0].number')
          if [ -n "$existing_pr" ]; then
            echo "PR already exists: #$existing_pr"
            exit 0
          fi
      - name: Create Pull Request
        run: |
          gh pr create \
            --base develop \
            --head image-updates \
            --title "Automated image updates" \
            --body "This PR contains automated updates to image versions." \
            || echo "Failed to create PR"
            