name: Create PR for Image Updates
on:
  push:
    branches:
      - image-updates
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
          gh pr create \
            --base test-wallet \
            --head image-updates \
            --title "Automated image updates" \
            --body "This PR contains automated updates to image versions." \
            || echo "PR already exists or cannot be created"

