name: Create PR for Image Updates

on:
  push:
    branches:
      - image-updates

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token --hostname github.com
          gh auth status

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --base develop \
            --head image-updates \
            --title "Automated image updates" \
            --body "This PR contains automated updates to image versions." \
            || echo "PR already exists or cannot be created"
