name: Create PR for Image Updates

on:
  push:
    branches:
      - image-updates

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for Existing PR
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:image-updates&base=develop&state=open")
          
          pr_number=$(echo "$pr_response" | jq '.[0].number // empty')
          echo "Found PR #: $pr_number"
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

      - name: Create Pull Request (via REST API)
        if: steps.check_pr.outputs.pr_number == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Automated image updates",
              "head": "image-updates",
              "base": "develop",
              "body": "This PR contains automated updates to image versions."
            }'
